//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


class glfw3PINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="SWIGRegisterExceptionCallbacks_glfw3")]
    public static extern void SWIGRegisterExceptionCallbacks_glfw3(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_glfw3")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_glfw3(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_glfw3(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_glfw3(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(glfw3PINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(glfw3PINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="SWIGRegisterStringCallback_glfw3")]
    public static extern void SWIGRegisterStringCallback_glfw3(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_glfw3(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static glfw3PINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_VERSION_MAJOR_get")]
  public static extern int GLFW_VERSION_MAJOR_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_VERSION_MINOR_get")]
  public static extern int GLFW_VERSION_MINOR_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_VERSION_REVISION_get")]
  public static extern int GLFW_VERSION_REVISION_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_TRUE_get")]
  public static extern int GLFW_TRUE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_FALSE_get")]
  public static extern int GLFW_FALSE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_RELEASE_get")]
  public static extern int GLFW_RELEASE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_PRESS_get")]
  public static extern int GLFW_PRESS_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_REPEAT_get")]
  public static extern int GLFW_REPEAT_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_HAT_CENTERED_get")]
  public static extern int GLFW_HAT_CENTERED_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_HAT_UP_get")]
  public static extern int GLFW_HAT_UP_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_HAT_RIGHT_get")]
  public static extern int GLFW_HAT_RIGHT_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_HAT_DOWN_get")]
  public static extern int GLFW_HAT_DOWN_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_HAT_LEFT_get")]
  public static extern int GLFW_HAT_LEFT_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_HAT_RIGHT_UP_get")]
  public static extern int GLFW_HAT_RIGHT_UP_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_HAT_RIGHT_DOWN_get")]
  public static extern int GLFW_HAT_RIGHT_DOWN_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_HAT_LEFT_UP_get")]
  public static extern int GLFW_HAT_LEFT_UP_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_HAT_LEFT_DOWN_get")]
  public static extern int GLFW_HAT_LEFT_DOWN_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_UNKNOWN_get")]
  public static extern int GLFW_KEY_UNKNOWN_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_SPACE_get")]
  public static extern int GLFW_KEY_SPACE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_APOSTROPHE_get")]
  public static extern int GLFW_KEY_APOSTROPHE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_COMMA_get")]
  public static extern int GLFW_KEY_COMMA_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_MINUS_get")]
  public static extern int GLFW_KEY_MINUS_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_PERIOD_get")]
  public static extern int GLFW_KEY_PERIOD_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_SLASH_get")]
  public static extern int GLFW_KEY_SLASH_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_0_get")]
  public static extern int GLFW_KEY_0_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_1_get")]
  public static extern int GLFW_KEY_1_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_2_get")]
  public static extern int GLFW_KEY_2_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_3_get")]
  public static extern int GLFW_KEY_3_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_4_get")]
  public static extern int GLFW_KEY_4_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_5_get")]
  public static extern int GLFW_KEY_5_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_6_get")]
  public static extern int GLFW_KEY_6_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_7_get")]
  public static extern int GLFW_KEY_7_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_8_get")]
  public static extern int GLFW_KEY_8_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_9_get")]
  public static extern int GLFW_KEY_9_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_SEMICOLON_get")]
  public static extern int GLFW_KEY_SEMICOLON_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_EQUAL_get")]
  public static extern int GLFW_KEY_EQUAL_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_A_get")]
  public static extern int GLFW_KEY_A_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_B_get")]
  public static extern int GLFW_KEY_B_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_C_get")]
  public static extern int GLFW_KEY_C_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_D_get")]
  public static extern int GLFW_KEY_D_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_E_get")]
  public static extern int GLFW_KEY_E_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F_get")]
  public static extern int GLFW_KEY_F_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_G_get")]
  public static extern int GLFW_KEY_G_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_H_get")]
  public static extern int GLFW_KEY_H_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_I_get")]
  public static extern int GLFW_KEY_I_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_J_get")]
  public static extern int GLFW_KEY_J_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_K_get")]
  public static extern int GLFW_KEY_K_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_L_get")]
  public static extern int GLFW_KEY_L_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_M_get")]
  public static extern int GLFW_KEY_M_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_N_get")]
  public static extern int GLFW_KEY_N_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_O_get")]
  public static extern int GLFW_KEY_O_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_P_get")]
  public static extern int GLFW_KEY_P_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_Q_get")]
  public static extern int GLFW_KEY_Q_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_R_get")]
  public static extern int GLFW_KEY_R_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_S_get")]
  public static extern int GLFW_KEY_S_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_T_get")]
  public static extern int GLFW_KEY_T_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_U_get")]
  public static extern int GLFW_KEY_U_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_V_get")]
  public static extern int GLFW_KEY_V_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_W_get")]
  public static extern int GLFW_KEY_W_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_X_get")]
  public static extern int GLFW_KEY_X_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_Y_get")]
  public static extern int GLFW_KEY_Y_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_Z_get")]
  public static extern int GLFW_KEY_Z_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_LEFT_BRACKET_get")]
  public static extern int GLFW_KEY_LEFT_BRACKET_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_BACKSLASH_get")]
  public static extern int GLFW_KEY_BACKSLASH_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_RIGHT_BRACKET_get")]
  public static extern int GLFW_KEY_RIGHT_BRACKET_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_GRAVE_ACCENT_get")]
  public static extern int GLFW_KEY_GRAVE_ACCENT_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_WORLD_1_get")]
  public static extern int GLFW_KEY_WORLD_1_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_WORLD_2_get")]
  public static extern int GLFW_KEY_WORLD_2_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_ESCAPE_get")]
  public static extern int GLFW_KEY_ESCAPE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_ENTER_get")]
  public static extern int GLFW_KEY_ENTER_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_TAB_get")]
  public static extern int GLFW_KEY_TAB_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_BACKSPACE_get")]
  public static extern int GLFW_KEY_BACKSPACE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_INSERT_get")]
  public static extern int GLFW_KEY_INSERT_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_DELETE_get")]
  public static extern int GLFW_KEY_DELETE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_RIGHT_get")]
  public static extern int GLFW_KEY_RIGHT_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_LEFT_get")]
  public static extern int GLFW_KEY_LEFT_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_DOWN_get")]
  public static extern int GLFW_KEY_DOWN_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_UP_get")]
  public static extern int GLFW_KEY_UP_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_PAGE_UP_get")]
  public static extern int GLFW_KEY_PAGE_UP_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_PAGE_DOWN_get")]
  public static extern int GLFW_KEY_PAGE_DOWN_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_HOME_get")]
  public static extern int GLFW_KEY_HOME_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_END_get")]
  public static extern int GLFW_KEY_END_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_CAPS_LOCK_get")]
  public static extern int GLFW_KEY_CAPS_LOCK_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_SCROLL_LOCK_get")]
  public static extern int GLFW_KEY_SCROLL_LOCK_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_NUM_LOCK_get")]
  public static extern int GLFW_KEY_NUM_LOCK_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_PRINT_SCREEN_get")]
  public static extern int GLFW_KEY_PRINT_SCREEN_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_PAUSE_get")]
  public static extern int GLFW_KEY_PAUSE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F1_get")]
  public static extern int GLFW_KEY_F1_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F2_get")]
  public static extern int GLFW_KEY_F2_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F3_get")]
  public static extern int GLFW_KEY_F3_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F4_get")]
  public static extern int GLFW_KEY_F4_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F5_get")]
  public static extern int GLFW_KEY_F5_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F6_get")]
  public static extern int GLFW_KEY_F6_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F7_get")]
  public static extern int GLFW_KEY_F7_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F8_get")]
  public static extern int GLFW_KEY_F8_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F9_get")]
  public static extern int GLFW_KEY_F9_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F10_get")]
  public static extern int GLFW_KEY_F10_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F11_get")]
  public static extern int GLFW_KEY_F11_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F12_get")]
  public static extern int GLFW_KEY_F12_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F13_get")]
  public static extern int GLFW_KEY_F13_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F14_get")]
  public static extern int GLFW_KEY_F14_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F15_get")]
  public static extern int GLFW_KEY_F15_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F16_get")]
  public static extern int GLFW_KEY_F16_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F17_get")]
  public static extern int GLFW_KEY_F17_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F18_get")]
  public static extern int GLFW_KEY_F18_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F19_get")]
  public static extern int GLFW_KEY_F19_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F20_get")]
  public static extern int GLFW_KEY_F20_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F21_get")]
  public static extern int GLFW_KEY_F21_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F22_get")]
  public static extern int GLFW_KEY_F22_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F23_get")]
  public static extern int GLFW_KEY_F23_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F24_get")]
  public static extern int GLFW_KEY_F24_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_F25_get")]
  public static extern int GLFW_KEY_F25_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_KP_0_get")]
  public static extern int GLFW_KEY_KP_0_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_KP_1_get")]
  public static extern int GLFW_KEY_KP_1_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_KP_2_get")]
  public static extern int GLFW_KEY_KP_2_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_KP_3_get")]
  public static extern int GLFW_KEY_KP_3_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_KP_4_get")]
  public static extern int GLFW_KEY_KP_4_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_KP_5_get")]
  public static extern int GLFW_KEY_KP_5_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_KP_6_get")]
  public static extern int GLFW_KEY_KP_6_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_KP_7_get")]
  public static extern int GLFW_KEY_KP_7_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_KP_8_get")]
  public static extern int GLFW_KEY_KP_8_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_KP_9_get")]
  public static extern int GLFW_KEY_KP_9_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_KP_DECIMAL_get")]
  public static extern int GLFW_KEY_KP_DECIMAL_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_KP_DIVIDE_get")]
  public static extern int GLFW_KEY_KP_DIVIDE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_KP_MULTIPLY_get")]
  public static extern int GLFW_KEY_KP_MULTIPLY_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_KP_SUBTRACT_get")]
  public static extern int GLFW_KEY_KP_SUBTRACT_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_KP_ADD_get")]
  public static extern int GLFW_KEY_KP_ADD_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_KP_ENTER_get")]
  public static extern int GLFW_KEY_KP_ENTER_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_KP_EQUAL_get")]
  public static extern int GLFW_KEY_KP_EQUAL_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_LEFT_SHIFT_get")]
  public static extern int GLFW_KEY_LEFT_SHIFT_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_LEFT_CONTROL_get")]
  public static extern int GLFW_KEY_LEFT_CONTROL_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_LEFT_ALT_get")]
  public static extern int GLFW_KEY_LEFT_ALT_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_LEFT_SUPER_get")]
  public static extern int GLFW_KEY_LEFT_SUPER_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_RIGHT_SHIFT_get")]
  public static extern int GLFW_KEY_RIGHT_SHIFT_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_RIGHT_CONTROL_get")]
  public static extern int GLFW_KEY_RIGHT_CONTROL_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_RIGHT_ALT_get")]
  public static extern int GLFW_KEY_RIGHT_ALT_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_RIGHT_SUPER_get")]
  public static extern int GLFW_KEY_RIGHT_SUPER_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_MENU_get")]
  public static extern int GLFW_KEY_MENU_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_KEY_LAST_get")]
  public static extern int GLFW_KEY_LAST_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_MOD_SHIFT_get")]
  public static extern int GLFW_MOD_SHIFT_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_MOD_CONTROL_get")]
  public static extern int GLFW_MOD_CONTROL_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_MOD_ALT_get")]
  public static extern int GLFW_MOD_ALT_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_MOD_SUPER_get")]
  public static extern int GLFW_MOD_SUPER_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_MOUSE_BUTTON_1_get")]
  public static extern int GLFW_MOUSE_BUTTON_1_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_MOUSE_BUTTON_2_get")]
  public static extern int GLFW_MOUSE_BUTTON_2_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_MOUSE_BUTTON_3_get")]
  public static extern int GLFW_MOUSE_BUTTON_3_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_MOUSE_BUTTON_4_get")]
  public static extern int GLFW_MOUSE_BUTTON_4_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_MOUSE_BUTTON_5_get")]
  public static extern int GLFW_MOUSE_BUTTON_5_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_MOUSE_BUTTON_6_get")]
  public static extern int GLFW_MOUSE_BUTTON_6_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_MOUSE_BUTTON_7_get")]
  public static extern int GLFW_MOUSE_BUTTON_7_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_MOUSE_BUTTON_8_get")]
  public static extern int GLFW_MOUSE_BUTTON_8_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_MOUSE_BUTTON_LAST_get")]
  public static extern int GLFW_MOUSE_BUTTON_LAST_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_MOUSE_BUTTON_LEFT_get")]
  public static extern int GLFW_MOUSE_BUTTON_LEFT_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_MOUSE_BUTTON_RIGHT_get")]
  public static extern int GLFW_MOUSE_BUTTON_RIGHT_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_MOUSE_BUTTON_MIDDLE_get")]
  public static extern int GLFW_MOUSE_BUTTON_MIDDLE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_JOYSTICK_1_get")]
  public static extern int GLFW_JOYSTICK_1_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_JOYSTICK_2_get")]
  public static extern int GLFW_JOYSTICK_2_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_JOYSTICK_3_get")]
  public static extern int GLFW_JOYSTICK_3_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_JOYSTICK_4_get")]
  public static extern int GLFW_JOYSTICK_4_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_JOYSTICK_5_get")]
  public static extern int GLFW_JOYSTICK_5_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_JOYSTICK_6_get")]
  public static extern int GLFW_JOYSTICK_6_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_JOYSTICK_7_get")]
  public static extern int GLFW_JOYSTICK_7_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_JOYSTICK_8_get")]
  public static extern int GLFW_JOYSTICK_8_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_JOYSTICK_9_get")]
  public static extern int GLFW_JOYSTICK_9_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_JOYSTICK_10_get")]
  public static extern int GLFW_JOYSTICK_10_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_JOYSTICK_11_get")]
  public static extern int GLFW_JOYSTICK_11_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_JOYSTICK_12_get")]
  public static extern int GLFW_JOYSTICK_12_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_JOYSTICK_13_get")]
  public static extern int GLFW_JOYSTICK_13_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_JOYSTICK_14_get")]
  public static extern int GLFW_JOYSTICK_14_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_JOYSTICK_15_get")]
  public static extern int GLFW_JOYSTICK_15_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_JOYSTICK_16_get")]
  public static extern int GLFW_JOYSTICK_16_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_JOYSTICK_LAST_get")]
  public static extern int GLFW_JOYSTICK_LAST_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_BUTTON_A_get")]
  public static extern int GLFW_GAMEPAD_BUTTON_A_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_BUTTON_B_get")]
  public static extern int GLFW_GAMEPAD_BUTTON_B_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_BUTTON_X_get")]
  public static extern int GLFW_GAMEPAD_BUTTON_X_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_BUTTON_Y_get")]
  public static extern int GLFW_GAMEPAD_BUTTON_Y_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_BUTTON_LEFT_BUMPER_get")]
  public static extern int GLFW_GAMEPAD_BUTTON_LEFT_BUMPER_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER_get")]
  public static extern int GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_BUTTON_BACK_get")]
  public static extern int GLFW_GAMEPAD_BUTTON_BACK_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_BUTTON_START_get")]
  public static extern int GLFW_GAMEPAD_BUTTON_START_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_BUTTON_GUIDE_get")]
  public static extern int GLFW_GAMEPAD_BUTTON_GUIDE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_BUTTON_LEFT_THUMB_get")]
  public static extern int GLFW_GAMEPAD_BUTTON_LEFT_THUMB_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_BUTTON_RIGHT_THUMB_get")]
  public static extern int GLFW_GAMEPAD_BUTTON_RIGHT_THUMB_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_BUTTON_DPAD_UP_get")]
  public static extern int GLFW_GAMEPAD_BUTTON_DPAD_UP_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_BUTTON_DPAD_RIGHT_get")]
  public static extern int GLFW_GAMEPAD_BUTTON_DPAD_RIGHT_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_BUTTON_DPAD_DOWN_get")]
  public static extern int GLFW_GAMEPAD_BUTTON_DPAD_DOWN_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_BUTTON_DPAD_LEFT_get")]
  public static extern int GLFW_GAMEPAD_BUTTON_DPAD_LEFT_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_BUTTON_LAST_get")]
  public static extern int GLFW_GAMEPAD_BUTTON_LAST_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_BUTTON_CROSS_get")]
  public static extern int GLFW_GAMEPAD_BUTTON_CROSS_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_BUTTON_CIRCLE_get")]
  public static extern int GLFW_GAMEPAD_BUTTON_CIRCLE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_BUTTON_SQUARE_get")]
  public static extern int GLFW_GAMEPAD_BUTTON_SQUARE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_BUTTON_TRIANGLE_get")]
  public static extern int GLFW_GAMEPAD_BUTTON_TRIANGLE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_AXIS_LEFT_X_get")]
  public static extern int GLFW_GAMEPAD_AXIS_LEFT_X_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_AXIS_LEFT_Y_get")]
  public static extern int GLFW_GAMEPAD_AXIS_LEFT_Y_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_AXIS_RIGHT_X_get")]
  public static extern int GLFW_GAMEPAD_AXIS_RIGHT_X_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_AXIS_RIGHT_Y_get")]
  public static extern int GLFW_GAMEPAD_AXIS_RIGHT_Y_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_AXIS_LEFT_TRIGGER_get")]
  public static extern int GLFW_GAMEPAD_AXIS_LEFT_TRIGGER_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER_get")]
  public static extern int GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GAMEPAD_AXIS_LAST_get")]
  public static extern int GLFW_GAMEPAD_AXIS_LAST_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_NO_ERROR_get")]
  public static extern int GLFW_NO_ERROR_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_NOT_INITIALIZED_get")]
  public static extern int GLFW_NOT_INITIALIZED_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_NO_CURRENT_CONTEXT_get")]
  public static extern int GLFW_NO_CURRENT_CONTEXT_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_INVALID_ENUM_get")]
  public static extern int GLFW_INVALID_ENUM_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_INVALID_VALUE_get")]
  public static extern int GLFW_INVALID_VALUE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_OUT_OF_MEMORY_get")]
  public static extern int GLFW_OUT_OF_MEMORY_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_API_UNAVAILABLE_get")]
  public static extern int GLFW_API_UNAVAILABLE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_VERSION_UNAVAILABLE_get")]
  public static extern int GLFW_VERSION_UNAVAILABLE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_PLATFORM_ERROR_get")]
  public static extern int GLFW_PLATFORM_ERROR_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_FORMAT_UNAVAILABLE_get")]
  public static extern int GLFW_FORMAT_UNAVAILABLE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_NO_WINDOW_CONTEXT_get")]
  public static extern int GLFW_NO_WINDOW_CONTEXT_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_FOCUSED_get")]
  public static extern int GLFW_FOCUSED_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_ICONIFIED_get")]
  public static extern int GLFW_ICONIFIED_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_RESIZABLE_get")]
  public static extern int GLFW_RESIZABLE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_VISIBLE_get")]
  public static extern int GLFW_VISIBLE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_DECORATED_get")]
  public static extern int GLFW_DECORATED_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_AUTO_ICONIFY_get")]
  public static extern int GLFW_AUTO_ICONIFY_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_FLOATING_get")]
  public static extern int GLFW_FLOATING_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_MAXIMIZED_get")]
  public static extern int GLFW_MAXIMIZED_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_CENTER_CURSOR_get")]
  public static extern int GLFW_CENTER_CURSOR_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_TRANSPARENT_get")]
  public static extern int GLFW_TRANSPARENT_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_RED_BITS_get")]
  public static extern int GLFW_RED_BITS_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_GREEN_BITS_get")]
  public static extern int GLFW_GREEN_BITS_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_BLUE_BITS_get")]
  public static extern int GLFW_BLUE_BITS_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_ALPHA_BITS_get")]
  public static extern int GLFW_ALPHA_BITS_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_DEPTH_BITS_get")]
  public static extern int GLFW_DEPTH_BITS_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_STENCIL_BITS_get")]
  public static extern int GLFW_STENCIL_BITS_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_ACCUM_RED_BITS_get")]
  public static extern int GLFW_ACCUM_RED_BITS_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_ACCUM_GREEN_BITS_get")]
  public static extern int GLFW_ACCUM_GREEN_BITS_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_ACCUM_BLUE_BITS_get")]
  public static extern int GLFW_ACCUM_BLUE_BITS_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_ACCUM_ALPHA_BITS_get")]
  public static extern int GLFW_ACCUM_ALPHA_BITS_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_AUX_BUFFERS_get")]
  public static extern int GLFW_AUX_BUFFERS_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_STEREO_get")]
  public static extern int GLFW_STEREO_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_SAMPLES_get")]
  public static extern int GLFW_SAMPLES_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_SRGB_CAPABLE_get")]
  public static extern int GLFW_SRGB_CAPABLE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_REFRESH_RATE_get")]
  public static extern int GLFW_REFRESH_RATE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_DOUBLEBUFFER_get")]
  public static extern int GLFW_DOUBLEBUFFER_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_CLIENT_API_get")]
  public static extern int GLFW_CLIENT_API_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_CONTEXT_VERSION_MAJOR_get")]
  public static extern int GLFW_CONTEXT_VERSION_MAJOR_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_CONTEXT_VERSION_MINOR_get")]
  public static extern int GLFW_CONTEXT_VERSION_MINOR_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_CONTEXT_REVISION_get")]
  public static extern int GLFW_CONTEXT_REVISION_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_CONTEXT_ROBUSTNESS_get")]
  public static extern int GLFW_CONTEXT_ROBUSTNESS_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_OPENGL_FORWARD_COMPAT_get")]
  public static extern int GLFW_OPENGL_FORWARD_COMPAT_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_OPENGL_DEBUG_CONTEXT_get")]
  public static extern int GLFW_OPENGL_DEBUG_CONTEXT_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_OPENGL_PROFILE_get")]
  public static extern int GLFW_OPENGL_PROFILE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_CONTEXT_RELEASE_BEHAVIOR_get")]
  public static extern int GLFW_CONTEXT_RELEASE_BEHAVIOR_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_CONTEXT_NO_ERROR_get")]
  public static extern int GLFW_CONTEXT_NO_ERROR_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_CONTEXT_CREATION_API_get")]
  public static extern int GLFW_CONTEXT_CREATION_API_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_COCOA_RETINA_FRAMEBUFFER_get")]
  public static extern int GLFW_COCOA_RETINA_FRAMEBUFFER_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_COCOA_FRAME_AUTOSAVE_get")]
  public static extern int GLFW_COCOA_FRAME_AUTOSAVE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_COCOA_GRAPHICS_SWITCHING_get")]
  public static extern int GLFW_COCOA_GRAPHICS_SWITCHING_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_NO_API_get")]
  public static extern int GLFW_NO_API_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_OPENGL_API_get")]
  public static extern int GLFW_OPENGL_API_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_OPENGL_ES_API_get")]
  public static extern int GLFW_OPENGL_ES_API_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_NO_ROBUSTNESS_get")]
  public static extern int GLFW_NO_ROBUSTNESS_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_NO_RESET_NOTIFICATION_get")]
  public static extern int GLFW_NO_RESET_NOTIFICATION_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_LOSE_CONTEXT_ON_RESET_get")]
  public static extern int GLFW_LOSE_CONTEXT_ON_RESET_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_OPENGL_ANY_PROFILE_get")]
  public static extern int GLFW_OPENGL_ANY_PROFILE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_OPENGL_CORE_PROFILE_get")]
  public static extern int GLFW_OPENGL_CORE_PROFILE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_OPENGL_COMPAT_PROFILE_get")]
  public static extern int GLFW_OPENGL_COMPAT_PROFILE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_CURSOR_get")]
  public static extern int GLFW_CURSOR_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_STICKY_KEYS_get")]
  public static extern int GLFW_STICKY_KEYS_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_STICKY_MOUSE_BUTTONS_get")]
  public static extern int GLFW_STICKY_MOUSE_BUTTONS_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_CURSOR_NORMAL_get")]
  public static extern int GLFW_CURSOR_NORMAL_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_CURSOR_HIDDEN_get")]
  public static extern int GLFW_CURSOR_HIDDEN_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_CURSOR_DISABLED_get")]
  public static extern int GLFW_CURSOR_DISABLED_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_ANY_RELEASE_BEHAVIOR_get")]
  public static extern int GLFW_ANY_RELEASE_BEHAVIOR_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_RELEASE_BEHAVIOR_FLUSH_get")]
  public static extern int GLFW_RELEASE_BEHAVIOR_FLUSH_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_RELEASE_BEHAVIOR_NONE_get")]
  public static extern int GLFW_RELEASE_BEHAVIOR_NONE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_NATIVE_CONTEXT_API_get")]
  public static extern int GLFW_NATIVE_CONTEXT_API_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_EGL_CONTEXT_API_get")]
  public static extern int GLFW_EGL_CONTEXT_API_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_OSMESA_CONTEXT_API_get")]
  public static extern int GLFW_OSMESA_CONTEXT_API_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_ARROW_CURSOR_get")]
  public static extern int GLFW_ARROW_CURSOR_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_IBEAM_CURSOR_get")]
  public static extern int GLFW_IBEAM_CURSOR_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_CROSSHAIR_CURSOR_get")]
  public static extern int GLFW_CROSSHAIR_CURSOR_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_HAND_CURSOR_get")]
  public static extern int GLFW_HAND_CURSOR_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_HRESIZE_CURSOR_get")]
  public static extern int GLFW_HRESIZE_CURSOR_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_VRESIZE_CURSOR_get")]
  public static extern int GLFW_VRESIZE_CURSOR_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_CONNECTED_get")]
  public static extern int GLFW_CONNECTED_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_DISCONNECTED_get")]
  public static extern int GLFW_DISCONNECTED_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_JOYSTICK_HAT_BUTTONS_get")]
  public static extern int GLFW_JOYSTICK_HAT_BUTTONS_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_COCOA_CHDIR_RESOURCES_get")]
  public static extern int GLFW_COCOA_CHDIR_RESOURCES_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_COCOA_MENUBAR_get")]
  public static extern int GLFW_COCOA_MENUBAR_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_X11_WM_CLASS_NAME_get")]
  public static extern int GLFW_X11_WM_CLASS_NAME_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_X11_WM_CLASS_CLASS_get")]
  public static extern int GLFW_X11_WM_CLASS_CLASS_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFW_DONT_CARE_get")]
  public static extern int GLFW_DONT_CARE_get();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWvidmode_width_set")]
  public static extern void GLFWvidmode_width_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWvidmode_width_get")]
  public static extern int GLFWvidmode_width_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWvidmode_height_set")]
  public static extern void GLFWvidmode_height_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWvidmode_height_get")]
  public static extern int GLFWvidmode_height_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWvidmode_redBits_set")]
  public static extern void GLFWvidmode_redBits_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWvidmode_redBits_get")]
  public static extern int GLFWvidmode_redBits_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWvidmode_greenBits_set")]
  public static extern void GLFWvidmode_greenBits_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWvidmode_greenBits_get")]
  public static extern int GLFWvidmode_greenBits_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWvidmode_blueBits_set")]
  public static extern void GLFWvidmode_blueBits_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWvidmode_blueBits_get")]
  public static extern int GLFWvidmode_blueBits_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWvidmode_refreshRate_set")]
  public static extern void GLFWvidmode_refreshRate_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWvidmode_refreshRate_get")]
  public static extern int GLFWvidmode_refreshRate_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_new_GLFWvidmode")]
  public static extern global::System.IntPtr new_GLFWvidmode();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_delete_GLFWvidmode")]
  public static extern void delete_GLFWvidmode(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWgammaramp_red_set")]
  public static extern void GLFWgammaramp_red_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWgammaramp_red_get")]
  public static extern global::System.IntPtr GLFWgammaramp_red_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWgammaramp_green_set")]
  public static extern void GLFWgammaramp_green_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWgammaramp_green_get")]
  public static extern global::System.IntPtr GLFWgammaramp_green_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWgammaramp_blue_set")]
  public static extern void GLFWgammaramp_blue_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWgammaramp_blue_get")]
  public static extern global::System.IntPtr GLFWgammaramp_blue_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWgammaramp_size_set")]
  public static extern void GLFWgammaramp_size_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWgammaramp_size_get")]
  public static extern uint GLFWgammaramp_size_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_new_GLFWgammaramp")]
  public static extern global::System.IntPtr new_GLFWgammaramp();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_delete_GLFWgammaramp")]
  public static extern void delete_GLFWgammaramp(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWimage_width_set")]
  public static extern void GLFWimage_width_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWimage_width_get")]
  public static extern int GLFWimage_width_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWimage_height_set")]
  public static extern void GLFWimage_height_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWimage_height_get")]
  public static extern int GLFWimage_height_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWimage_pixels_set")]
  public static extern void GLFWimage_pixels_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWimage_pixels_get")]
  public static extern global::System.IntPtr GLFWimage_pixels_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_new_GLFWimage")]
  public static extern global::System.IntPtr new_GLFWimage();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_delete_GLFWimage")]
  public static extern void delete_GLFWimage(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWgamepadstate_buttons_set")]
  public static extern void GLFWgamepadstate_buttons_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWgamepadstate_buttons_get")]
  public static extern global::System.IntPtr GLFWgamepadstate_buttons_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWgamepadstate_axes_set")]
  public static extern void GLFWgamepadstate_axes_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_GLFWgamepadstate_axes_get")]
  public static extern global::System.IntPtr GLFWgamepadstate_axes_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_new_GLFWgamepadstate")]
  public static extern global::System.IntPtr new_GLFWgamepadstate();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_delete_GLFWgamepadstate")]
  public static extern void delete_GLFWgamepadstate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwInit")]
  public static extern int glfwInit();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwTerminate")]
  public static extern void glfwTerminate();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwInitHint")]
  public static extern void glfwInitHint(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwInitHintString")]
  public static extern void glfwInitHintString(int jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetVersion")]
  public static extern void glfwGetVersion(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetVersionString")]
  public static extern string glfwGetVersionString();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetError")]
  public static extern int glfwGetError(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetErrorCallback")]
  public static extern global::System.IntPtr glfwSetErrorCallback(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetMonitors")]
  public static extern global::System.IntPtr glfwGetMonitors(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetPrimaryMonitor")]
  public static extern global::System.IntPtr glfwGetPrimaryMonitor();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetMonitorPos")]
  public static extern void glfwGetMonitorPos(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetMonitorPhysicalSize")]
  public static extern void glfwGetMonitorPhysicalSize(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetMonitorName")]
  public static extern string glfwGetMonitorName(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetMonitorCallback")]
  public static extern global::System.IntPtr glfwSetMonitorCallback(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetVideoModes")]
  public static extern global::System.IntPtr glfwGetVideoModes(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetVideoMode")]
  public static extern global::System.IntPtr glfwGetVideoMode(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetGamma")]
  public static extern void glfwSetGamma(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetGammaRamp")]
  public static extern global::System.IntPtr glfwGetGammaRamp(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetGammaRamp")]
  public static extern void glfwSetGammaRamp(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwDefaultWindowHints")]
  public static extern void glfwDefaultWindowHints();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwWindowHint")]
  public static extern void glfwWindowHint(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwCreateWindow")]
  public static extern global::System.IntPtr glfwCreateWindow(int jarg1, int jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwDestroyWindow")]
  public static extern void glfwDestroyWindow(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwWindowShouldClose")]
  public static extern int glfwWindowShouldClose(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetWindowShouldClose")]
  public static extern void glfwSetWindowShouldClose(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetWindowTitle")]
  public static extern void glfwSetWindowTitle(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetWindowIcon")]
  public static extern void glfwSetWindowIcon(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetWindowPos")]
  public static extern void glfwGetWindowPos(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetWindowPos")]
  public static extern void glfwSetWindowPos(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetWindowSize")]
  public static extern void glfwGetWindowSize(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetWindowSizeLimits")]
  public static extern void glfwSetWindowSizeLimits(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4, int jarg5);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetWindowAspectRatio")]
  public static extern void glfwSetWindowAspectRatio(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetWindowSize")]
  public static extern void glfwSetWindowSize(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetFramebufferSize")]
  public static extern void glfwGetFramebufferSize(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetWindowFrameSize")]
  public static extern void glfwGetWindowFrameSize(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwIconifyWindow")]
  public static extern void glfwIconifyWindow(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwRestoreWindow")]
  public static extern void glfwRestoreWindow(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwMaximizeWindow")]
  public static extern void glfwMaximizeWindow(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwShowWindow")]
  public static extern void glfwShowWindow(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwHideWindow")]
  public static extern void glfwHideWindow(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwFocusWindow")]
  public static extern void glfwFocusWindow(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwRequestWindowAttention")]
  public static extern void glfwRequestWindowAttention(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetWindowMonitor")]
  public static extern global::System.IntPtr glfwGetWindowMonitor(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetWindowMonitor")]
  public static extern void glfwSetWindowMonitor(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetWindowAttrib")]
  public static extern int glfwGetWindowAttrib(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetWindowAttrib")]
  public static extern void glfwSetWindowAttrib(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetWindowUserPointer")]
  public static extern void glfwSetWindowUserPointer(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetWindowUserPointer")]
  public static extern global::System.IntPtr glfwGetWindowUserPointer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetWindowPosCallback")]
  public static extern global::System.IntPtr glfwSetWindowPosCallback(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetWindowSizeCallback")]
  public static extern global::System.IntPtr glfwSetWindowSizeCallback(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetWindowCloseCallback")]
  public static extern global::System.IntPtr glfwSetWindowCloseCallback(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetWindowRefreshCallback")]
  public static extern global::System.IntPtr glfwSetWindowRefreshCallback(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetWindowFocusCallback")]
  public static extern global::System.IntPtr glfwSetWindowFocusCallback(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetWindowIconifyCallback")]
  public static extern global::System.IntPtr glfwSetWindowIconifyCallback(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetWindowMaximizeCallback")]
  public static extern global::System.IntPtr glfwSetWindowMaximizeCallback(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetFramebufferSizeCallback")]
  public static extern global::System.IntPtr glfwSetFramebufferSizeCallback(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwPollEvents")]
  public static extern void glfwPollEvents();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwWaitEvents")]
  public static extern void glfwWaitEvents();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwWaitEventsTimeout")]
  public static extern void glfwWaitEventsTimeout(double jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwPostEmptyEvent")]
  public static extern void glfwPostEmptyEvent();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetInputMode")]
  public static extern int glfwGetInputMode(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetInputMode")]
  public static extern void glfwSetInputMode(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetKeyName")]
  public static extern string glfwGetKeyName(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetKeyScancode")]
  public static extern int glfwGetKeyScancode(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetKey")]
  public static extern int glfwGetKey(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetMouseButton")]
  public static extern int glfwGetMouseButton(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetCursorPos")]
  public static extern void glfwGetCursorPos(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetCursorPos")]
  public static extern void glfwSetCursorPos(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwCreateCursor")]
  public static extern global::System.IntPtr glfwCreateCursor(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwCreateStandardCursor")]
  public static extern global::System.IntPtr glfwCreateStandardCursor(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwDestroyCursor")]
  public static extern void glfwDestroyCursor(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetCursor")]
  public static extern void glfwSetCursor(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetKeyCallback")]
  public static extern global::System.IntPtr glfwSetKeyCallback(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetCharCallback")]
  public static extern global::System.IntPtr glfwSetCharCallback(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetCharModsCallback")]
  public static extern global::System.IntPtr glfwSetCharModsCallback(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetMouseButtonCallback")]
  public static extern global::System.IntPtr glfwSetMouseButtonCallback(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetCursorPosCallback")]
  public static extern global::System.IntPtr glfwSetCursorPosCallback(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetCursorEnterCallback")]
  public static extern global::System.IntPtr glfwSetCursorEnterCallback(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetScrollCallback")]
  public static extern global::System.IntPtr glfwSetScrollCallback(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetDropCallback")]
  public static extern global::System.IntPtr glfwSetDropCallback(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwJoystickPresent")]
  public static extern int glfwJoystickPresent(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetJoystickAxes")]
  public static extern global::System.IntPtr glfwGetJoystickAxes(int jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetJoystickButtons")]
  public static extern global::System.IntPtr glfwGetJoystickButtons(int jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetJoystickHats")]
  public static extern global::System.IntPtr glfwGetJoystickHats(int jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetJoystickName")]
  public static extern string glfwGetJoystickName(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetJoystickGUID")]
  public static extern string glfwGetJoystickGUID(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwJoystickIsGamepad")]
  public static extern int glfwJoystickIsGamepad(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetJoystickCallback")]
  public static extern global::System.IntPtr glfwSetJoystickCallback(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwUpdateGamepadMappings")]
  public static extern int glfwUpdateGamepadMappings(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetGamepadName")]
  public static extern string glfwGetGamepadName(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetGamepadState")]
  public static extern int glfwGetGamepadState(int jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetClipboardString")]
  public static extern void glfwSetClipboardString(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetClipboardString")]
  public static extern string glfwGetClipboardString(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetTime")]
  public static extern double glfwGetTime();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSetTime")]
  public static extern void glfwSetTime(double jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetTimerValue")]
  public static extern global::System.IntPtr glfwGetTimerValue();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetTimerFrequency")]
  public static extern global::System.IntPtr glfwGetTimerFrequency();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwMakeContextCurrent")]
  public static extern void glfwMakeContextCurrent(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetCurrentContext")]
  public static extern global::System.IntPtr glfwGetCurrentContext();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSwapBuffers")]
  public static extern void glfwSwapBuffers(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwSwapInterval")]
  public static extern void glfwSwapInterval(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwExtensionSupported")]
  public static extern int glfwExtensionSupported(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetProcAddress")]
  public static extern global::System.IntPtr glfwGetProcAddress(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwVulkanSupported")]
  public static extern int glfwVulkanSupported();

  [global::System.Runtime.InteropServices.DllImport("glfw3", EntryPoint="CSharp_glfwGetRequiredInstanceExtensions")]
  public static extern global::System.IntPtr glfwGetRequiredInstanceExtensions(global::System.Runtime.InteropServices.HandleRef jarg1);
}
