//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class GLFWvidmode : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GLFWvidmode(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GLFWvidmode obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GLFWvidmode() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          glfw3PINVOKE.delete_GLFWvidmode(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int width {
    set {
      glfw3PINVOKE.GLFWvidmode_width_set(swigCPtr, value);
    } 
    get {
      int ret = glfw3PINVOKE.GLFWvidmode_width_get(swigCPtr);
      return ret;
    } 
  }

  public int height {
    set {
      glfw3PINVOKE.GLFWvidmode_height_set(swigCPtr, value);
    } 
    get {
      int ret = glfw3PINVOKE.GLFWvidmode_height_get(swigCPtr);
      return ret;
    } 
  }

  public int redBits {
    set {
      glfw3PINVOKE.GLFWvidmode_redBits_set(swigCPtr, value);
    } 
    get {
      int ret = glfw3PINVOKE.GLFWvidmode_redBits_get(swigCPtr);
      return ret;
    } 
  }

  public int greenBits {
    set {
      glfw3PINVOKE.GLFWvidmode_greenBits_set(swigCPtr, value);
    } 
    get {
      int ret = glfw3PINVOKE.GLFWvidmode_greenBits_get(swigCPtr);
      return ret;
    } 
  }

  public int blueBits {
    set {
      glfw3PINVOKE.GLFWvidmode_blueBits_set(swigCPtr, value);
    } 
    get {
      int ret = glfw3PINVOKE.GLFWvidmode_blueBits_get(swigCPtr);
      return ret;
    } 
  }

  public int refreshRate {
    set {
      glfw3PINVOKE.GLFWvidmode_refreshRate_set(swigCPtr, value);
    } 
    get {
      int ret = glfw3PINVOKE.GLFWvidmode_refreshRate_get(swigCPtr);
      return ret;
    } 
  }

  public GLFWvidmode() : this(glfw3PINVOKE.new_GLFWvidmode(), true) {
  }

}
