/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGCSHARP
#define SWIGCSHARP
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_glfw3(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_glfw3(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_glfw3(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else


    #include "glfw3.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_VERSION_MAJOR_get() {
  int jresult ;
  int result;
  
  result = (int)(3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_VERSION_MINOR_get() {
  int jresult ;
  int result;
  
  result = (int)(3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_VERSION_REVISION_get() {
  int jresult ;
  int result;
  
  result = (int)(0);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_TRUE_get() {
  int jresult ;
  int result;
  
  result = (int)(1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_FALSE_get() {
  int jresult ;
  int result;
  
  result = (int)(0);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_RELEASE_get() {
  int jresult ;
  int result;
  
  result = (int)(0);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_PRESS_get() {
  int jresult ;
  int result;
  
  result = (int)(1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_REPEAT_get() {
  int jresult ;
  int result;
  
  result = (int)(2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_HAT_CENTERED_get() {
  int jresult ;
  int result;
  
  result = (int)(0);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_HAT_UP_get() {
  int jresult ;
  int result;
  
  result = (int)(1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_HAT_RIGHT_get() {
  int jresult ;
  int result;
  
  result = (int)(2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_HAT_DOWN_get() {
  int jresult ;
  int result;
  
  result = (int)(4);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_HAT_LEFT_get() {
  int jresult ;
  int result;
  
  result = (int)(8);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_HAT_RIGHT_UP_get() {
  int jresult ;
  int result;
  
  result = (int)((2|1));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_HAT_RIGHT_DOWN_get() {
  int jresult ;
  int result;
  
  result = (int)((2|4));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_HAT_LEFT_UP_get() {
  int jresult ;
  int result;
  
  result = (int)((8|1));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_HAT_LEFT_DOWN_get() {
  int jresult ;
  int result;
  
  result = (int)((8|4));
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_UNKNOWN_get() {
  int jresult ;
  int result;
  
  result = (int)(-1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_SPACE_get() {
  int jresult ;
  int result;
  
  result = (int)(32);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_APOSTROPHE_get() {
  int jresult ;
  int result;
  
  result = (int)(39);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_COMMA_get() {
  int jresult ;
  int result;
  
  result = (int)(44);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_MINUS_get() {
  int jresult ;
  int result;
  
  result = (int)(45);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_PERIOD_get() {
  int jresult ;
  int result;
  
  result = (int)(46);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_SLASH_get() {
  int jresult ;
  int result;
  
  result = (int)(47);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_0_get() {
  int jresult ;
  int result;
  
  result = (int)(48);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_1_get() {
  int jresult ;
  int result;
  
  result = (int)(49);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_2_get() {
  int jresult ;
  int result;
  
  result = (int)(50);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_3_get() {
  int jresult ;
  int result;
  
  result = (int)(51);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_4_get() {
  int jresult ;
  int result;
  
  result = (int)(52);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_5_get() {
  int jresult ;
  int result;
  
  result = (int)(53);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_6_get() {
  int jresult ;
  int result;
  
  result = (int)(54);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_7_get() {
  int jresult ;
  int result;
  
  result = (int)(55);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_8_get() {
  int jresult ;
  int result;
  
  result = (int)(56);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_9_get() {
  int jresult ;
  int result;
  
  result = (int)(57);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_SEMICOLON_get() {
  int jresult ;
  int result;
  
  result = (int)(59);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_EQUAL_get() {
  int jresult ;
  int result;
  
  result = (int)(61);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_A_get() {
  int jresult ;
  int result;
  
  result = (int)(65);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_B_get() {
  int jresult ;
  int result;
  
  result = (int)(66);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_C_get() {
  int jresult ;
  int result;
  
  result = (int)(67);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_D_get() {
  int jresult ;
  int result;
  
  result = (int)(68);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_E_get() {
  int jresult ;
  int result;
  
  result = (int)(69);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F_get() {
  int jresult ;
  int result;
  
  result = (int)(70);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_G_get() {
  int jresult ;
  int result;
  
  result = (int)(71);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_H_get() {
  int jresult ;
  int result;
  
  result = (int)(72);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_I_get() {
  int jresult ;
  int result;
  
  result = (int)(73);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_J_get() {
  int jresult ;
  int result;
  
  result = (int)(74);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_K_get() {
  int jresult ;
  int result;
  
  result = (int)(75);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_L_get() {
  int jresult ;
  int result;
  
  result = (int)(76);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_M_get() {
  int jresult ;
  int result;
  
  result = (int)(77);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_N_get() {
  int jresult ;
  int result;
  
  result = (int)(78);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_O_get() {
  int jresult ;
  int result;
  
  result = (int)(79);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_P_get() {
  int jresult ;
  int result;
  
  result = (int)(80);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_Q_get() {
  int jresult ;
  int result;
  
  result = (int)(81);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_R_get() {
  int jresult ;
  int result;
  
  result = (int)(82);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_S_get() {
  int jresult ;
  int result;
  
  result = (int)(83);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_T_get() {
  int jresult ;
  int result;
  
  result = (int)(84);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_U_get() {
  int jresult ;
  int result;
  
  result = (int)(85);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_V_get() {
  int jresult ;
  int result;
  
  result = (int)(86);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_W_get() {
  int jresult ;
  int result;
  
  result = (int)(87);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_X_get() {
  int jresult ;
  int result;
  
  result = (int)(88);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_Y_get() {
  int jresult ;
  int result;
  
  result = (int)(89);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_Z_get() {
  int jresult ;
  int result;
  
  result = (int)(90);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_LEFT_BRACKET_get() {
  int jresult ;
  int result;
  
  result = (int)(91);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_BACKSLASH_get() {
  int jresult ;
  int result;
  
  result = (int)(92);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_RIGHT_BRACKET_get() {
  int jresult ;
  int result;
  
  result = (int)(93);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_GRAVE_ACCENT_get() {
  int jresult ;
  int result;
  
  result = (int)(96);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_WORLD_1_get() {
  int jresult ;
  int result;
  
  result = (int)(161);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_WORLD_2_get() {
  int jresult ;
  int result;
  
  result = (int)(162);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_ESCAPE_get() {
  int jresult ;
  int result;
  
  result = (int)(256);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_ENTER_get() {
  int jresult ;
  int result;
  
  result = (int)(257);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_TAB_get() {
  int jresult ;
  int result;
  
  result = (int)(258);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_BACKSPACE_get() {
  int jresult ;
  int result;
  
  result = (int)(259);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_INSERT_get() {
  int jresult ;
  int result;
  
  result = (int)(260);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_DELETE_get() {
  int jresult ;
  int result;
  
  result = (int)(261);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_RIGHT_get() {
  int jresult ;
  int result;
  
  result = (int)(262);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_LEFT_get() {
  int jresult ;
  int result;
  
  result = (int)(263);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_DOWN_get() {
  int jresult ;
  int result;
  
  result = (int)(264);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_UP_get() {
  int jresult ;
  int result;
  
  result = (int)(265);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_PAGE_UP_get() {
  int jresult ;
  int result;
  
  result = (int)(266);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_PAGE_DOWN_get() {
  int jresult ;
  int result;
  
  result = (int)(267);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_HOME_get() {
  int jresult ;
  int result;
  
  result = (int)(268);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_END_get() {
  int jresult ;
  int result;
  
  result = (int)(269);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_CAPS_LOCK_get() {
  int jresult ;
  int result;
  
  result = (int)(280);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_SCROLL_LOCK_get() {
  int jresult ;
  int result;
  
  result = (int)(281);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_NUM_LOCK_get() {
  int jresult ;
  int result;
  
  result = (int)(282);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_PRINT_SCREEN_get() {
  int jresult ;
  int result;
  
  result = (int)(283);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_PAUSE_get() {
  int jresult ;
  int result;
  
  result = (int)(284);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F1_get() {
  int jresult ;
  int result;
  
  result = (int)(290);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F2_get() {
  int jresult ;
  int result;
  
  result = (int)(291);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F3_get() {
  int jresult ;
  int result;
  
  result = (int)(292);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F4_get() {
  int jresult ;
  int result;
  
  result = (int)(293);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F5_get() {
  int jresult ;
  int result;
  
  result = (int)(294);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F6_get() {
  int jresult ;
  int result;
  
  result = (int)(295);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F7_get() {
  int jresult ;
  int result;
  
  result = (int)(296);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F8_get() {
  int jresult ;
  int result;
  
  result = (int)(297);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F9_get() {
  int jresult ;
  int result;
  
  result = (int)(298);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F10_get() {
  int jresult ;
  int result;
  
  result = (int)(299);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F11_get() {
  int jresult ;
  int result;
  
  result = (int)(300);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F12_get() {
  int jresult ;
  int result;
  
  result = (int)(301);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F13_get() {
  int jresult ;
  int result;
  
  result = (int)(302);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F14_get() {
  int jresult ;
  int result;
  
  result = (int)(303);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F15_get() {
  int jresult ;
  int result;
  
  result = (int)(304);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F16_get() {
  int jresult ;
  int result;
  
  result = (int)(305);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F17_get() {
  int jresult ;
  int result;
  
  result = (int)(306);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F18_get() {
  int jresult ;
  int result;
  
  result = (int)(307);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F19_get() {
  int jresult ;
  int result;
  
  result = (int)(308);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F20_get() {
  int jresult ;
  int result;
  
  result = (int)(309);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F21_get() {
  int jresult ;
  int result;
  
  result = (int)(310);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F22_get() {
  int jresult ;
  int result;
  
  result = (int)(311);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F23_get() {
  int jresult ;
  int result;
  
  result = (int)(312);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F24_get() {
  int jresult ;
  int result;
  
  result = (int)(313);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_F25_get() {
  int jresult ;
  int result;
  
  result = (int)(314);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_KP_0_get() {
  int jresult ;
  int result;
  
  result = (int)(320);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_KP_1_get() {
  int jresult ;
  int result;
  
  result = (int)(321);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_KP_2_get() {
  int jresult ;
  int result;
  
  result = (int)(322);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_KP_3_get() {
  int jresult ;
  int result;
  
  result = (int)(323);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_KP_4_get() {
  int jresult ;
  int result;
  
  result = (int)(324);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_KP_5_get() {
  int jresult ;
  int result;
  
  result = (int)(325);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_KP_6_get() {
  int jresult ;
  int result;
  
  result = (int)(326);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_KP_7_get() {
  int jresult ;
  int result;
  
  result = (int)(327);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_KP_8_get() {
  int jresult ;
  int result;
  
  result = (int)(328);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_KP_9_get() {
  int jresult ;
  int result;
  
  result = (int)(329);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_KP_DECIMAL_get() {
  int jresult ;
  int result;
  
  result = (int)(330);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_KP_DIVIDE_get() {
  int jresult ;
  int result;
  
  result = (int)(331);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_KP_MULTIPLY_get() {
  int jresult ;
  int result;
  
  result = (int)(332);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_KP_SUBTRACT_get() {
  int jresult ;
  int result;
  
  result = (int)(333);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_KP_ADD_get() {
  int jresult ;
  int result;
  
  result = (int)(334);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_KP_ENTER_get() {
  int jresult ;
  int result;
  
  result = (int)(335);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_KP_EQUAL_get() {
  int jresult ;
  int result;
  
  result = (int)(336);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_LEFT_SHIFT_get() {
  int jresult ;
  int result;
  
  result = (int)(340);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_LEFT_CONTROL_get() {
  int jresult ;
  int result;
  
  result = (int)(341);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_LEFT_ALT_get() {
  int jresult ;
  int result;
  
  result = (int)(342);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_LEFT_SUPER_get() {
  int jresult ;
  int result;
  
  result = (int)(343);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_RIGHT_SHIFT_get() {
  int jresult ;
  int result;
  
  result = (int)(344);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_RIGHT_CONTROL_get() {
  int jresult ;
  int result;
  
  result = (int)(345);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_RIGHT_ALT_get() {
  int jresult ;
  int result;
  
  result = (int)(346);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_RIGHT_SUPER_get() {
  int jresult ;
  int result;
  
  result = (int)(347);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_MENU_get() {
  int jresult ;
  int result;
  
  result = (int)(348);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_KEY_LAST_get() {
  int jresult ;
  int result;
  
  result = (int)(348);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_MOD_SHIFT_get() {
  int jresult ;
  int result;
  
  result = (int)(0x0001);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_MOD_CONTROL_get() {
  int jresult ;
  int result;
  
  result = (int)(0x0002);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_MOD_ALT_get() {
  int jresult ;
  int result;
  
  result = (int)(0x0004);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_MOD_SUPER_get() {
  int jresult ;
  int result;
  
  result = (int)(0x0008);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_MOUSE_BUTTON_1_get() {
  int jresult ;
  int result;
  
  result = (int)(0);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_MOUSE_BUTTON_2_get() {
  int jresult ;
  int result;
  
  result = (int)(1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_MOUSE_BUTTON_3_get() {
  int jresult ;
  int result;
  
  result = (int)(2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_MOUSE_BUTTON_4_get() {
  int jresult ;
  int result;
  
  result = (int)(3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_MOUSE_BUTTON_5_get() {
  int jresult ;
  int result;
  
  result = (int)(4);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_MOUSE_BUTTON_6_get() {
  int jresult ;
  int result;
  
  result = (int)(5);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_MOUSE_BUTTON_7_get() {
  int jresult ;
  int result;
  
  result = (int)(6);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_MOUSE_BUTTON_8_get() {
  int jresult ;
  int result;
  
  result = (int)(7);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_MOUSE_BUTTON_LAST_get() {
  int jresult ;
  int result;
  
  result = (int)(7);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_MOUSE_BUTTON_LEFT_get() {
  int jresult ;
  int result;
  
  result = (int)(0);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_MOUSE_BUTTON_RIGHT_get() {
  int jresult ;
  int result;
  
  result = (int)(1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_MOUSE_BUTTON_MIDDLE_get() {
  int jresult ;
  int result;
  
  result = (int)(2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_JOYSTICK_1_get() {
  int jresult ;
  int result;
  
  result = (int)(0);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_JOYSTICK_2_get() {
  int jresult ;
  int result;
  
  result = (int)(1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_JOYSTICK_3_get() {
  int jresult ;
  int result;
  
  result = (int)(2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_JOYSTICK_4_get() {
  int jresult ;
  int result;
  
  result = (int)(3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_JOYSTICK_5_get() {
  int jresult ;
  int result;
  
  result = (int)(4);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_JOYSTICK_6_get() {
  int jresult ;
  int result;
  
  result = (int)(5);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_JOYSTICK_7_get() {
  int jresult ;
  int result;
  
  result = (int)(6);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_JOYSTICK_8_get() {
  int jresult ;
  int result;
  
  result = (int)(7);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_JOYSTICK_9_get() {
  int jresult ;
  int result;
  
  result = (int)(8);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_JOYSTICK_10_get() {
  int jresult ;
  int result;
  
  result = (int)(9);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_JOYSTICK_11_get() {
  int jresult ;
  int result;
  
  result = (int)(10);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_JOYSTICK_12_get() {
  int jresult ;
  int result;
  
  result = (int)(11);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_JOYSTICK_13_get() {
  int jresult ;
  int result;
  
  result = (int)(12);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_JOYSTICK_14_get() {
  int jresult ;
  int result;
  
  result = (int)(13);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_JOYSTICK_15_get() {
  int jresult ;
  int result;
  
  result = (int)(14);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_JOYSTICK_16_get() {
  int jresult ;
  int result;
  
  result = (int)(15);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_JOYSTICK_LAST_get() {
  int jresult ;
  int result;
  
  result = (int)(15);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_BUTTON_A_get() {
  int jresult ;
  int result;
  
  result = (int)(0);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_BUTTON_B_get() {
  int jresult ;
  int result;
  
  result = (int)(1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_BUTTON_X_get() {
  int jresult ;
  int result;
  
  result = (int)(2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_BUTTON_Y_get() {
  int jresult ;
  int result;
  
  result = (int)(3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_BUTTON_LEFT_BUMPER_get() {
  int jresult ;
  int result;
  
  result = (int)(4);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER_get() {
  int jresult ;
  int result;
  
  result = (int)(5);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_BUTTON_BACK_get() {
  int jresult ;
  int result;
  
  result = (int)(6);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_BUTTON_START_get() {
  int jresult ;
  int result;
  
  result = (int)(7);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_BUTTON_GUIDE_get() {
  int jresult ;
  int result;
  
  result = (int)(8);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_BUTTON_LEFT_THUMB_get() {
  int jresult ;
  int result;
  
  result = (int)(9);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_BUTTON_RIGHT_THUMB_get() {
  int jresult ;
  int result;
  
  result = (int)(10);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_BUTTON_DPAD_UP_get() {
  int jresult ;
  int result;
  
  result = (int)(11);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_BUTTON_DPAD_RIGHT_get() {
  int jresult ;
  int result;
  
  result = (int)(12);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_BUTTON_DPAD_DOWN_get() {
  int jresult ;
  int result;
  
  result = (int)(13);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_BUTTON_DPAD_LEFT_get() {
  int jresult ;
  int result;
  
  result = (int)(14);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_BUTTON_LAST_get() {
  int jresult ;
  int result;
  
  result = (int)(14);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_BUTTON_CROSS_get() {
  int jresult ;
  int result;
  
  result = (int)(0);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_BUTTON_CIRCLE_get() {
  int jresult ;
  int result;
  
  result = (int)(1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_BUTTON_SQUARE_get() {
  int jresult ;
  int result;
  
  result = (int)(2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_BUTTON_TRIANGLE_get() {
  int jresult ;
  int result;
  
  result = (int)(3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_AXIS_LEFT_X_get() {
  int jresult ;
  int result;
  
  result = (int)(0);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_AXIS_LEFT_Y_get() {
  int jresult ;
  int result;
  
  result = (int)(1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_AXIS_RIGHT_X_get() {
  int jresult ;
  int result;
  
  result = (int)(2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_AXIS_RIGHT_Y_get() {
  int jresult ;
  int result;
  
  result = (int)(3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_AXIS_LEFT_TRIGGER_get() {
  int jresult ;
  int result;
  
  result = (int)(4);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER_get() {
  int jresult ;
  int result;
  
  result = (int)(5);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GAMEPAD_AXIS_LAST_get() {
  int jresult ;
  int result;
  
  result = (int)(5);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_NO_ERROR_get() {
  int jresult ;
  int result;
  
  result = (int)(0);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_NOT_INITIALIZED_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00010001);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_NO_CURRENT_CONTEXT_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00010002);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_INVALID_ENUM_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00010003);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_INVALID_VALUE_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00010004);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_OUT_OF_MEMORY_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00010005);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_API_UNAVAILABLE_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00010006);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_VERSION_UNAVAILABLE_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00010007);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_PLATFORM_ERROR_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00010008);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_FORMAT_UNAVAILABLE_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00010009);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_NO_WINDOW_CONTEXT_get() {
  int jresult ;
  int result;
  
  result = (int)(0x0001000A);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_FOCUSED_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00020001);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_ICONIFIED_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00020002);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_RESIZABLE_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00020003);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_VISIBLE_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00020004);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_DECORATED_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00020005);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_AUTO_ICONIFY_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00020006);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_FLOATING_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00020007);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_MAXIMIZED_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00020008);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_CENTER_CURSOR_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00020009);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_TRANSPARENT_get() {
  int jresult ;
  int result;
  
  result = (int)(0x0002000A);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_RED_BITS_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00021001);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_GREEN_BITS_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00021002);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_BLUE_BITS_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00021003);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_ALPHA_BITS_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00021004);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_DEPTH_BITS_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00021005);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_STENCIL_BITS_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00021006);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_ACCUM_RED_BITS_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00021007);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_ACCUM_GREEN_BITS_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00021008);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_ACCUM_BLUE_BITS_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00021009);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_ACCUM_ALPHA_BITS_get() {
  int jresult ;
  int result;
  
  result = (int)(0x0002100A);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_AUX_BUFFERS_get() {
  int jresult ;
  int result;
  
  result = (int)(0x0002100B);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_STEREO_get() {
  int jresult ;
  int result;
  
  result = (int)(0x0002100C);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_SAMPLES_get() {
  int jresult ;
  int result;
  
  result = (int)(0x0002100D);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_SRGB_CAPABLE_get() {
  int jresult ;
  int result;
  
  result = (int)(0x0002100E);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_REFRESH_RATE_get() {
  int jresult ;
  int result;
  
  result = (int)(0x0002100F);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_DOUBLEBUFFER_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00021010);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_CLIENT_API_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00022001);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_CONTEXT_VERSION_MAJOR_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00022002);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_CONTEXT_VERSION_MINOR_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00022003);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_CONTEXT_REVISION_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00022004);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_CONTEXT_ROBUSTNESS_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00022005);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_OPENGL_FORWARD_COMPAT_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00022006);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_OPENGL_DEBUG_CONTEXT_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00022007);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_OPENGL_PROFILE_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00022008);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_CONTEXT_RELEASE_BEHAVIOR_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00022009);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_CONTEXT_NO_ERROR_get() {
  int jresult ;
  int result;
  
  result = (int)(0x0002200A);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_CONTEXT_CREATION_API_get() {
  int jresult ;
  int result;
  
  result = (int)(0x0002200B);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_COCOA_RETINA_FRAMEBUFFER_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00023001);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_COCOA_FRAME_AUTOSAVE_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00023002);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_COCOA_GRAPHICS_SWITCHING_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00023003);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_NO_API_get() {
  int jresult ;
  int result;
  
  result = (int)(0);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_OPENGL_API_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00030001);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_OPENGL_ES_API_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00030002);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_NO_ROBUSTNESS_get() {
  int jresult ;
  int result;
  
  result = (int)(0);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_NO_RESET_NOTIFICATION_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00031001);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_LOSE_CONTEXT_ON_RESET_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00031002);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_OPENGL_ANY_PROFILE_get() {
  int jresult ;
  int result;
  
  result = (int)(0);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_OPENGL_CORE_PROFILE_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00032001);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_OPENGL_COMPAT_PROFILE_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00032002);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_CURSOR_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00033001);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_STICKY_KEYS_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00033002);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_STICKY_MOUSE_BUTTONS_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00033003);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_CURSOR_NORMAL_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00034001);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_CURSOR_HIDDEN_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00034002);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_CURSOR_DISABLED_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00034003);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_ANY_RELEASE_BEHAVIOR_get() {
  int jresult ;
  int result;
  
  result = (int)(0);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_RELEASE_BEHAVIOR_FLUSH_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00035001);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_RELEASE_BEHAVIOR_NONE_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00035002);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_NATIVE_CONTEXT_API_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00036001);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_EGL_CONTEXT_API_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00036002);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_OSMESA_CONTEXT_API_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00036003);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_ARROW_CURSOR_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00036001);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_IBEAM_CURSOR_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00036002);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_CROSSHAIR_CURSOR_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00036003);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_HAND_CURSOR_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00036004);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_HRESIZE_CURSOR_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00036005);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_VRESIZE_CURSOR_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00036006);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_CONNECTED_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00040001);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_DISCONNECTED_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00040002);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_JOYSTICK_HAT_BUTTONS_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00050001);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_COCOA_CHDIR_RESOURCES_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00051001);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_COCOA_MENUBAR_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00051002);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_X11_WM_CLASS_NAME_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00052001);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_X11_WM_CLASS_CLASS_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00052002);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFW_DONT_CARE_get() {
  int jresult ;
  int result;
  
  result = (int)(-1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_GLFWvidmode_width_set(void * jarg1, int jarg2) {
  struct GLFWvidmode *arg1 = (struct GLFWvidmode *) 0 ;
  int arg2 ;
  
  arg1 = (struct GLFWvidmode *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->width = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFWvidmode_width_get(void * jarg1) {
  int jresult ;
  struct GLFWvidmode *arg1 = (struct GLFWvidmode *) 0 ;
  int result;
  
  arg1 = (struct GLFWvidmode *)jarg1; 
  result = (int) ((arg1)->width);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_GLFWvidmode_height_set(void * jarg1, int jarg2) {
  struct GLFWvidmode *arg1 = (struct GLFWvidmode *) 0 ;
  int arg2 ;
  
  arg1 = (struct GLFWvidmode *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->height = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFWvidmode_height_get(void * jarg1) {
  int jresult ;
  struct GLFWvidmode *arg1 = (struct GLFWvidmode *) 0 ;
  int result;
  
  arg1 = (struct GLFWvidmode *)jarg1; 
  result = (int) ((arg1)->height);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_GLFWvidmode_redBits_set(void * jarg1, int jarg2) {
  struct GLFWvidmode *arg1 = (struct GLFWvidmode *) 0 ;
  int arg2 ;
  
  arg1 = (struct GLFWvidmode *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->redBits = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFWvidmode_redBits_get(void * jarg1) {
  int jresult ;
  struct GLFWvidmode *arg1 = (struct GLFWvidmode *) 0 ;
  int result;
  
  arg1 = (struct GLFWvidmode *)jarg1; 
  result = (int) ((arg1)->redBits);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_GLFWvidmode_greenBits_set(void * jarg1, int jarg2) {
  struct GLFWvidmode *arg1 = (struct GLFWvidmode *) 0 ;
  int arg2 ;
  
  arg1 = (struct GLFWvidmode *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->greenBits = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFWvidmode_greenBits_get(void * jarg1) {
  int jresult ;
  struct GLFWvidmode *arg1 = (struct GLFWvidmode *) 0 ;
  int result;
  
  arg1 = (struct GLFWvidmode *)jarg1; 
  result = (int) ((arg1)->greenBits);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_GLFWvidmode_blueBits_set(void * jarg1, int jarg2) {
  struct GLFWvidmode *arg1 = (struct GLFWvidmode *) 0 ;
  int arg2 ;
  
  arg1 = (struct GLFWvidmode *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->blueBits = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFWvidmode_blueBits_get(void * jarg1) {
  int jresult ;
  struct GLFWvidmode *arg1 = (struct GLFWvidmode *) 0 ;
  int result;
  
  arg1 = (struct GLFWvidmode *)jarg1; 
  result = (int) ((arg1)->blueBits);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_GLFWvidmode_refreshRate_set(void * jarg1, int jarg2) {
  struct GLFWvidmode *arg1 = (struct GLFWvidmode *) 0 ;
  int arg2 ;
  
  arg1 = (struct GLFWvidmode *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->refreshRate = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFWvidmode_refreshRate_get(void * jarg1) {
  int jresult ;
  struct GLFWvidmode *arg1 = (struct GLFWvidmode *) 0 ;
  int result;
  
  arg1 = (struct GLFWvidmode *)jarg1; 
  result = (int) ((arg1)->refreshRate);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_GLFWvidmode() {
  void * jresult ;
  struct GLFWvidmode *result = 0 ;
  
  result = (struct GLFWvidmode *)calloc(1, sizeof(struct GLFWvidmode));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_GLFWvidmode(void * jarg1) {
  struct GLFWvidmode *arg1 = (struct GLFWvidmode *) 0 ;
  
  arg1 = (struct GLFWvidmode *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_GLFWgammaramp_red_set(void * jarg1, void * jarg2) {
  struct GLFWgammaramp *arg1 = (struct GLFWgammaramp *) 0 ;
  unsigned short *arg2 = (unsigned short *) 0 ;
  
  arg1 = (struct GLFWgammaramp *)jarg1; 
  arg2 = (unsigned short *)jarg2; 
  if (arg1) (arg1)->red = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_GLFWgammaramp_red_get(void * jarg1) {
  void * jresult ;
  struct GLFWgammaramp *arg1 = (struct GLFWgammaramp *) 0 ;
  unsigned short *result = 0 ;
  
  arg1 = (struct GLFWgammaramp *)jarg1; 
  result = (unsigned short *) ((arg1)->red);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_GLFWgammaramp_green_set(void * jarg1, void * jarg2) {
  struct GLFWgammaramp *arg1 = (struct GLFWgammaramp *) 0 ;
  unsigned short *arg2 = (unsigned short *) 0 ;
  
  arg1 = (struct GLFWgammaramp *)jarg1; 
  arg2 = (unsigned short *)jarg2; 
  if (arg1) (arg1)->green = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_GLFWgammaramp_green_get(void * jarg1) {
  void * jresult ;
  struct GLFWgammaramp *arg1 = (struct GLFWgammaramp *) 0 ;
  unsigned short *result = 0 ;
  
  arg1 = (struct GLFWgammaramp *)jarg1; 
  result = (unsigned short *) ((arg1)->green);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_GLFWgammaramp_blue_set(void * jarg1, void * jarg2) {
  struct GLFWgammaramp *arg1 = (struct GLFWgammaramp *) 0 ;
  unsigned short *arg2 = (unsigned short *) 0 ;
  
  arg1 = (struct GLFWgammaramp *)jarg1; 
  arg2 = (unsigned short *)jarg2; 
  if (arg1) (arg1)->blue = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_GLFWgammaramp_blue_get(void * jarg1) {
  void * jresult ;
  struct GLFWgammaramp *arg1 = (struct GLFWgammaramp *) 0 ;
  unsigned short *result = 0 ;
  
  arg1 = (struct GLFWgammaramp *)jarg1; 
  result = (unsigned short *) ((arg1)->blue);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_GLFWgammaramp_size_set(void * jarg1, unsigned int jarg2) {
  struct GLFWgammaramp *arg1 = (struct GLFWgammaramp *) 0 ;
  unsigned int arg2 ;
  
  arg1 = (struct GLFWgammaramp *)jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->size = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_GLFWgammaramp_size_get(void * jarg1) {
  unsigned int jresult ;
  struct GLFWgammaramp *arg1 = (struct GLFWgammaramp *) 0 ;
  unsigned int result;
  
  arg1 = (struct GLFWgammaramp *)jarg1; 
  result = (unsigned int) ((arg1)->size);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_GLFWgammaramp() {
  void * jresult ;
  struct GLFWgammaramp *result = 0 ;
  
  result = (struct GLFWgammaramp *)calloc(1, sizeof(struct GLFWgammaramp));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_GLFWgammaramp(void * jarg1) {
  struct GLFWgammaramp *arg1 = (struct GLFWgammaramp *) 0 ;
  
  arg1 = (struct GLFWgammaramp *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_GLFWimage_width_set(void * jarg1, int jarg2) {
  struct GLFWimage *arg1 = (struct GLFWimage *) 0 ;
  int arg2 ;
  
  arg1 = (struct GLFWimage *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->width = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFWimage_width_get(void * jarg1) {
  int jresult ;
  struct GLFWimage *arg1 = (struct GLFWimage *) 0 ;
  int result;
  
  arg1 = (struct GLFWimage *)jarg1; 
  result = (int) ((arg1)->width);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_GLFWimage_height_set(void * jarg1, int jarg2) {
  struct GLFWimage *arg1 = (struct GLFWimage *) 0 ;
  int arg2 ;
  
  arg1 = (struct GLFWimage *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->height = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_GLFWimage_height_get(void * jarg1) {
  int jresult ;
  struct GLFWimage *arg1 = (struct GLFWimage *) 0 ;
  int result;
  
  arg1 = (struct GLFWimage *)jarg1; 
  result = (int) ((arg1)->height);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_GLFWimage_pixels_set(void * jarg1, void * jarg2) {
  struct GLFWimage *arg1 = (struct GLFWimage *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  
  arg1 = (struct GLFWimage *)jarg1; 
  arg2 = (unsigned char *)jarg2; 
  if (arg1) (arg1)->pixels = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_GLFWimage_pixels_get(void * jarg1) {
  void * jresult ;
  struct GLFWimage *arg1 = (struct GLFWimage *) 0 ;
  unsigned char *result = 0 ;
  
  arg1 = (struct GLFWimage *)jarg1; 
  result = (unsigned char *) ((arg1)->pixels);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_GLFWimage() {
  void * jresult ;
  struct GLFWimage *result = 0 ;
  
  result = (struct GLFWimage *)calloc(1, sizeof(struct GLFWimage));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_GLFWimage(void * jarg1) {
  struct GLFWimage *arg1 = (struct GLFWimage *) 0 ;
  
  arg1 = (struct GLFWimage *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_GLFWgamepadstate_buttons_set(void * jarg1, void * jarg2) {
  struct GLFWgamepadstate *arg1 = (struct GLFWgamepadstate *) 0 ;
  unsigned char *arg2 ;
  
  arg1 = (struct GLFWgamepadstate *)jarg1; 
  arg2 = (unsigned char *)jarg2; 
  {
    size_t ii;
    unsigned char *b = (unsigned char *) arg1->buttons;
    for (ii = 0; ii < (size_t)15; ii++) b[ii] = *((unsigned char *) arg2 + ii);
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_GLFWgamepadstate_buttons_get(void * jarg1) {
  void * jresult ;
  struct GLFWgamepadstate *arg1 = (struct GLFWgamepadstate *) 0 ;
  unsigned char *result = 0 ;
  
  arg1 = (struct GLFWgamepadstate *)jarg1; 
  result = (unsigned char *)(unsigned char *) ((arg1)->buttons);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_GLFWgamepadstate_axes_set(void * jarg1, void * jarg2) {
  struct GLFWgamepadstate *arg1 = (struct GLFWgamepadstate *) 0 ;
  float *arg2 ;
  
  arg1 = (struct GLFWgamepadstate *)jarg1; 
  arg2 = (float *)jarg2; 
  {
    size_t ii;
    float *b = (float *) arg1->axes;
    for (ii = 0; ii < (size_t)6; ii++) b[ii] = *((float *) arg2 + ii);
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_GLFWgamepadstate_axes_get(void * jarg1) {
  void * jresult ;
  struct GLFWgamepadstate *arg1 = (struct GLFWgamepadstate *) 0 ;
  float *result = 0 ;
  
  arg1 = (struct GLFWgamepadstate *)jarg1; 
  result = (float *)(float *) ((arg1)->axes);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_GLFWgamepadstate() {
  void * jresult ;
  struct GLFWgamepadstate *result = 0 ;
  
  result = (struct GLFWgamepadstate *)calloc(1, sizeof(struct GLFWgamepadstate));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_GLFWgamepadstate(void * jarg1) {
  struct GLFWgamepadstate *arg1 = (struct GLFWgamepadstate *) 0 ;
  
  arg1 = (struct GLFWgamepadstate *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_glfwInit() {
  int jresult ;
  int result;
  
  result = (int)glfwInit();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwTerminate() {
  glfwTerminate();
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwInitHint(int jarg1, int jarg2) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  glfwInitHint(arg1,arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwInitHintString(int jarg1, char * jarg2) {
  int arg1 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (int)jarg1; 
  arg2 = (char *)jarg2; 
  glfwInitHintString(arg1,(char const *)arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwGetVersion(void * jarg1, void * jarg2, void * jarg3) {
  int *arg1 = (int *) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  
  arg1 = (int *)jarg1; 
  arg2 = (int *)jarg2; 
  arg3 = (int *)jarg3; 
  glfwGetVersion(arg1,arg2,arg3);
}


SWIGEXPORT char * SWIGSTDCALL CSharp_glfwGetVersionString() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *)glfwGetVersionString();
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_glfwGetError(void * jarg1) {
  int jresult ;
  char **arg1 = (char **) 0 ;
  int result;
  
  arg1 = (char **)jarg1; 
  result = (int)glfwGetError((char const **)arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwSetErrorCallback(void * jarg1) {
  void * jresult ;
  GLFWerrorfun arg1 = (GLFWerrorfun) 0 ;
  GLFWerrorfun result;
  
  arg1 = (GLFWerrorfun)jarg1; 
  result = (GLFWerrorfun)glfwSetErrorCallback(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwGetMonitors(void * jarg1) {
  void * jresult ;
  int *arg1 = (int *) 0 ;
  GLFWmonitor **result = 0 ;
  
  arg1 = (int *)jarg1; 
  result = (GLFWmonitor **)glfwGetMonitors(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwGetPrimaryMonitor() {
  void * jresult ;
  GLFWmonitor *result = 0 ;
  
  result = (GLFWmonitor *)glfwGetPrimaryMonitor();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwGetMonitorPos(void * jarg1, void * jarg2, void * jarg3) {
  GLFWmonitor *arg1 = (GLFWmonitor *) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  
  arg1 = (GLFWmonitor *)jarg1; 
  arg2 = (int *)jarg2; 
  arg3 = (int *)jarg3; 
  glfwGetMonitorPos(arg1,arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwGetMonitorPhysicalSize(void * jarg1, void * jarg2, void * jarg3) {
  GLFWmonitor *arg1 = (GLFWmonitor *) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  
  arg1 = (GLFWmonitor *)jarg1; 
  arg2 = (int *)jarg2; 
  arg3 = (int *)jarg3; 
  glfwGetMonitorPhysicalSize(arg1,arg2,arg3);
}


SWIGEXPORT char * SWIGSTDCALL CSharp_glfwGetMonitorName(void * jarg1) {
  char * jresult ;
  GLFWmonitor *arg1 = (GLFWmonitor *) 0 ;
  char *result = 0 ;
  
  arg1 = (GLFWmonitor *)jarg1; 
  result = (char *)glfwGetMonitorName(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwSetMonitorCallback(void * jarg1) {
  void * jresult ;
  GLFWmonitorfun arg1 = (GLFWmonitorfun) 0 ;
  GLFWmonitorfun result;
  
  arg1 = (GLFWmonitorfun)jarg1; 
  result = (GLFWmonitorfun)glfwSetMonitorCallback(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwGetVideoModes(void * jarg1, void * jarg2) {
  void * jresult ;
  GLFWmonitor *arg1 = (GLFWmonitor *) 0 ;
  int *arg2 = (int *) 0 ;
  GLFWvidmode *result = 0 ;
  
  arg1 = (GLFWmonitor *)jarg1; 
  arg2 = (int *)jarg2; 
  result = (GLFWvidmode *)glfwGetVideoModes(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwGetVideoMode(void * jarg1) {
  void * jresult ;
  GLFWmonitor *arg1 = (GLFWmonitor *) 0 ;
  GLFWvidmode *result = 0 ;
  
  arg1 = (GLFWmonitor *)jarg1; 
  result = (GLFWvidmode *)glfwGetVideoMode(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwSetGamma(void * jarg1, float jarg2) {
  GLFWmonitor *arg1 = (GLFWmonitor *) 0 ;
  float arg2 ;
  
  arg1 = (GLFWmonitor *)jarg1; 
  arg2 = (float)jarg2; 
  glfwSetGamma(arg1,arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwGetGammaRamp(void * jarg1) {
  void * jresult ;
  GLFWmonitor *arg1 = (GLFWmonitor *) 0 ;
  GLFWgammaramp *result = 0 ;
  
  arg1 = (GLFWmonitor *)jarg1; 
  result = (GLFWgammaramp *)glfwGetGammaRamp(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwSetGammaRamp(void * jarg1, void * jarg2) {
  GLFWmonitor *arg1 = (GLFWmonitor *) 0 ;
  GLFWgammaramp *arg2 = (GLFWgammaramp *) 0 ;
  
  arg1 = (GLFWmonitor *)jarg1; 
  arg2 = (GLFWgammaramp *)jarg2; 
  glfwSetGammaRamp(arg1,(struct GLFWgammaramp const *)arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwDefaultWindowHints() {
  glfwDefaultWindowHints();
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwWindowHint(int jarg1, int jarg2) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  glfwWindowHint(arg1,arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwCreateWindow(int jarg1, int jarg2, char * jarg3, void * jarg4, void * jarg5) {
  void * jresult ;
  int arg1 ;
  int arg2 ;
  char *arg3 = (char *) 0 ;
  GLFWmonitor *arg4 = (GLFWmonitor *) 0 ;
  GLFWwindow *arg5 = (GLFWwindow *) 0 ;
  GLFWwindow *result = 0 ;
  
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (char *)jarg3; 
  arg4 = (GLFWmonitor *)jarg4; 
  arg5 = (GLFWwindow *)jarg5; 
  result = (GLFWwindow *)glfwCreateWindow(arg1,arg2,(char const *)arg3,arg4,arg5);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwDestroyWindow(void * jarg1) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  glfwDestroyWindow(arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_glfwWindowShouldClose(void * jarg1) {
  int jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  int result;
  
  arg1 = (GLFWwindow *)jarg1; 
  result = (int)glfwWindowShouldClose(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwSetWindowShouldClose(void * jarg1, int jarg2) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  int arg2 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (int)jarg2; 
  glfwSetWindowShouldClose(arg1,arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwSetWindowTitle(void * jarg1, char * jarg2) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (char *)jarg2; 
  glfwSetWindowTitle(arg1,(char const *)arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwSetWindowIcon(void * jarg1, int jarg2, void * jarg3) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  int arg2 ;
  GLFWimage *arg3 = (GLFWimage *) 0 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (GLFWimage *)jarg3; 
  glfwSetWindowIcon(arg1,arg2,(struct GLFWimage const *)arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwGetWindowPos(void * jarg1, void * jarg2, void * jarg3) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (int *)jarg2; 
  arg3 = (int *)jarg3; 
  glfwGetWindowPos(arg1,arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwSetWindowPos(void * jarg1, int jarg2, int jarg3) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  glfwSetWindowPos(arg1,arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwGetWindowSize(void * jarg1, void * jarg2, void * jarg3) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (int *)jarg2; 
  arg3 = (int *)jarg3; 
  glfwGetWindowSize(arg1,arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwSetWindowSizeLimits(void * jarg1, int jarg2, int jarg3, int jarg4, int jarg5) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  int arg5 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = (int)jarg5; 
  glfwSetWindowSizeLimits(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwSetWindowAspectRatio(void * jarg1, int jarg2, int jarg3) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  glfwSetWindowAspectRatio(arg1,arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwSetWindowSize(void * jarg1, int jarg2, int jarg3) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  glfwSetWindowSize(arg1,arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwGetFramebufferSize(void * jarg1, void * jarg2, void * jarg3) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (int *)jarg2; 
  arg3 = (int *)jarg3; 
  glfwGetFramebufferSize(arg1,arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwGetWindowFrameSize(void * jarg1, void * jarg2, void * jarg3, void * jarg4, void * jarg5) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  int *arg4 = (int *) 0 ;
  int *arg5 = (int *) 0 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (int *)jarg2; 
  arg3 = (int *)jarg3; 
  arg4 = (int *)jarg4; 
  arg5 = (int *)jarg5; 
  glfwGetWindowFrameSize(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwIconifyWindow(void * jarg1) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  glfwIconifyWindow(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwRestoreWindow(void * jarg1) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  glfwRestoreWindow(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwMaximizeWindow(void * jarg1) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  glfwMaximizeWindow(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwShowWindow(void * jarg1) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  glfwShowWindow(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwHideWindow(void * jarg1) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  glfwHideWindow(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwFocusWindow(void * jarg1) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  glfwFocusWindow(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwRequestWindowAttention(void * jarg1) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  glfwRequestWindowAttention(arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwGetWindowMonitor(void * jarg1) {
  void * jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  GLFWmonitor *result = 0 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  result = (GLFWmonitor *)glfwGetWindowMonitor(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwSetWindowMonitor(void * jarg1, void * jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  GLFWmonitor *arg2 = (GLFWmonitor *) 0 ;
  int arg3 ;
  int arg4 ;
  int arg5 ;
  int arg6 ;
  int arg7 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (GLFWmonitor *)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = (int)jarg5; 
  arg6 = (int)jarg6; 
  arg7 = (int)jarg7; 
  glfwSetWindowMonitor(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
}


SWIGEXPORT int SWIGSTDCALL CSharp_glfwGetWindowAttrib(void * jarg1, int jarg2) {
  int jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  int arg2 ;
  int result;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (int)jarg2; 
  result = (int)glfwGetWindowAttrib(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwSetWindowAttrib(void * jarg1, int jarg2, int jarg3) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  glfwSetWindowAttrib(arg1,arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwSetWindowUserPointer(void * jarg1, void * jarg2) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  void *arg2 = (void *) 0 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (void *)jarg2; 
  glfwSetWindowUserPointer(arg1,arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwGetWindowUserPointer(void * jarg1) {
  void * jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  void *result = 0 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  result = (void *)glfwGetWindowUserPointer(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwSetWindowPosCallback(void * jarg1, void * jarg2) {
  void * jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  GLFWwindowposfun arg2 = (GLFWwindowposfun) 0 ;
  GLFWwindowposfun result;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (GLFWwindowposfun)jarg2; 
  result = (GLFWwindowposfun)glfwSetWindowPosCallback(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwSetWindowSizeCallback(void * jarg1, void * jarg2) {
  void * jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  GLFWwindowsizefun arg2 = (GLFWwindowsizefun) 0 ;
  GLFWwindowsizefun result;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (GLFWwindowsizefun)jarg2; 
  result = (GLFWwindowsizefun)glfwSetWindowSizeCallback(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwSetWindowCloseCallback(void * jarg1, void * jarg2) {
  void * jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  GLFWwindowclosefun arg2 = (GLFWwindowclosefun) 0 ;
  GLFWwindowclosefun result;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (GLFWwindowclosefun)jarg2; 
  result = (GLFWwindowclosefun)glfwSetWindowCloseCallback(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwSetWindowRefreshCallback(void * jarg1, void * jarg2) {
  void * jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  GLFWwindowrefreshfun arg2 = (GLFWwindowrefreshfun) 0 ;
  GLFWwindowrefreshfun result;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (GLFWwindowrefreshfun)jarg2; 
  result = (GLFWwindowrefreshfun)glfwSetWindowRefreshCallback(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwSetWindowFocusCallback(void * jarg1, void * jarg2) {
  void * jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  GLFWwindowfocusfun arg2 = (GLFWwindowfocusfun) 0 ;
  GLFWwindowfocusfun result;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (GLFWwindowfocusfun)jarg2; 
  result = (GLFWwindowfocusfun)glfwSetWindowFocusCallback(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwSetWindowIconifyCallback(void * jarg1, void * jarg2) {
  void * jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  GLFWwindowiconifyfun arg2 = (GLFWwindowiconifyfun) 0 ;
  GLFWwindowiconifyfun result;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (GLFWwindowiconifyfun)jarg2; 
  result = (GLFWwindowiconifyfun)glfwSetWindowIconifyCallback(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwSetWindowMaximizeCallback(void * jarg1, void * jarg2) {
  void * jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  GLFWwindowmaximizefun arg2 = (GLFWwindowmaximizefun) 0 ;
  GLFWwindowmaximizefun result;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (GLFWwindowmaximizefun)jarg2; 
  result = (GLFWwindowmaximizefun)glfwSetWindowMaximizeCallback(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwSetFramebufferSizeCallback(void * jarg1, void * jarg2) {
  void * jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  GLFWframebuffersizefun arg2 = (GLFWframebuffersizefun) 0 ;
  GLFWframebuffersizefun result;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (GLFWframebuffersizefun)jarg2; 
  result = (GLFWframebuffersizefun)glfwSetFramebufferSizeCallback(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwPollEvents() {
  glfwPollEvents();
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwWaitEvents() {
  glfwWaitEvents();
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwWaitEventsTimeout(double jarg1) {
  double arg1 ;
  
  arg1 = (double)jarg1; 
  glfwWaitEventsTimeout(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwPostEmptyEvent() {
  glfwPostEmptyEvent();
}


SWIGEXPORT int SWIGSTDCALL CSharp_glfwGetInputMode(void * jarg1, int jarg2) {
  int jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  int arg2 ;
  int result;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (int)jarg2; 
  result = (int)glfwGetInputMode(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwSetInputMode(void * jarg1, int jarg2, int jarg3) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  glfwSetInputMode(arg1,arg2,arg3);
}


SWIGEXPORT char * SWIGSTDCALL CSharp_glfwGetKeyName(int jarg1, int jarg2) {
  char * jresult ;
  int arg1 ;
  int arg2 ;
  char *result = 0 ;
  
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (char *)glfwGetKeyName(arg1,arg2);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_glfwGetKeyScancode(int jarg1) {
  int jresult ;
  int arg1 ;
  int result;
  
  arg1 = (int)jarg1; 
  result = (int)glfwGetKeyScancode(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_glfwGetKey(void * jarg1, int jarg2) {
  int jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  int arg2 ;
  int result;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (int)jarg2; 
  result = (int)glfwGetKey(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_glfwGetMouseButton(void * jarg1, int jarg2) {
  int jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  int arg2 ;
  int result;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (int)jarg2; 
  result = (int)glfwGetMouseButton(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwGetCursorPos(void * jarg1, void * jarg2, void * jarg3) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  double *arg2 = (double *) 0 ;
  double *arg3 = (double *) 0 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (double *)jarg2; 
  arg3 = (double *)jarg3; 
  glfwGetCursorPos(arg1,arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwSetCursorPos(void * jarg1, double jarg2, double jarg3) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  double arg2 ;
  double arg3 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (double)jarg2; 
  arg3 = (double)jarg3; 
  glfwSetCursorPos(arg1,arg2,arg3);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwCreateCursor(void * jarg1, int jarg2, int jarg3) {
  void * jresult ;
  GLFWimage *arg1 = (GLFWimage *) 0 ;
  int arg2 ;
  int arg3 ;
  GLFWcursor *result = 0 ;
  
  arg1 = (GLFWimage *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (GLFWcursor *)glfwCreateCursor((struct GLFWimage const *)arg1,arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwCreateStandardCursor(int jarg1) {
  void * jresult ;
  int arg1 ;
  GLFWcursor *result = 0 ;
  
  arg1 = (int)jarg1; 
  result = (GLFWcursor *)glfwCreateStandardCursor(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwDestroyCursor(void * jarg1) {
  GLFWcursor *arg1 = (GLFWcursor *) 0 ;
  
  arg1 = (GLFWcursor *)jarg1; 
  glfwDestroyCursor(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwSetCursor(void * jarg1, void * jarg2) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  GLFWcursor *arg2 = (GLFWcursor *) 0 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (GLFWcursor *)jarg2; 
  glfwSetCursor(arg1,arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwSetKeyCallback(void * jarg1, void * jarg2) {
  void * jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  GLFWkeyfun arg2 = (GLFWkeyfun) 0 ;
  GLFWkeyfun result;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (GLFWkeyfun)jarg2; 
  result = (GLFWkeyfun)glfwSetKeyCallback(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwSetCharCallback(void * jarg1, void * jarg2) {
  void * jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  GLFWcharfun arg2 = (GLFWcharfun) 0 ;
  GLFWcharfun result;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (GLFWcharfun)jarg2; 
  result = (GLFWcharfun)glfwSetCharCallback(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwSetCharModsCallback(void * jarg1, void * jarg2) {
  void * jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  GLFWcharmodsfun arg2 = (GLFWcharmodsfun) 0 ;
  GLFWcharmodsfun result;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (GLFWcharmodsfun)jarg2; 
  result = (GLFWcharmodsfun)glfwSetCharModsCallback(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwSetMouseButtonCallback(void * jarg1, void * jarg2) {
  void * jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  GLFWmousebuttonfun arg2 = (GLFWmousebuttonfun) 0 ;
  GLFWmousebuttonfun result;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (GLFWmousebuttonfun)jarg2; 
  result = (GLFWmousebuttonfun)glfwSetMouseButtonCallback(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwSetCursorPosCallback(void * jarg1, void * jarg2) {
  void * jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  GLFWcursorposfun arg2 = (GLFWcursorposfun) 0 ;
  GLFWcursorposfun result;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (GLFWcursorposfun)jarg2; 
  result = (GLFWcursorposfun)glfwSetCursorPosCallback(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwSetCursorEnterCallback(void * jarg1, void * jarg2) {
  void * jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  GLFWcursorenterfun arg2 = (GLFWcursorenterfun) 0 ;
  GLFWcursorenterfun result;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (GLFWcursorenterfun)jarg2; 
  result = (GLFWcursorenterfun)glfwSetCursorEnterCallback(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwSetScrollCallback(void * jarg1, void * jarg2) {
  void * jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  GLFWscrollfun arg2 = (GLFWscrollfun) 0 ;
  GLFWscrollfun result;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (GLFWscrollfun)jarg2; 
  result = (GLFWscrollfun)glfwSetScrollCallback(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwSetDropCallback(void * jarg1, void * jarg2) {
  void * jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  GLFWdropfun arg2 = (GLFWdropfun) 0 ;
  GLFWdropfun result;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (GLFWdropfun)jarg2; 
  result = (GLFWdropfun)glfwSetDropCallback(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_glfwJoystickPresent(int jarg1) {
  int jresult ;
  int arg1 ;
  int result;
  
  arg1 = (int)jarg1; 
  result = (int)glfwJoystickPresent(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwGetJoystickAxes(int jarg1, void * jarg2) {
  void * jresult ;
  int arg1 ;
  int *arg2 = (int *) 0 ;
  float *result = 0 ;
  
  arg1 = (int)jarg1; 
  arg2 = (int *)jarg2; 
  result = (float *)glfwGetJoystickAxes(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwGetJoystickButtons(int jarg1, void * jarg2) {
  void * jresult ;
  int arg1 ;
  int *arg2 = (int *) 0 ;
  unsigned char *result = 0 ;
  
  arg1 = (int)jarg1; 
  arg2 = (int *)jarg2; 
  result = (unsigned char *)glfwGetJoystickButtons(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwGetJoystickHats(int jarg1, void * jarg2) {
  void * jresult ;
  int arg1 ;
  int *arg2 = (int *) 0 ;
  unsigned char *result = 0 ;
  
  arg1 = (int)jarg1; 
  arg2 = (int *)jarg2; 
  result = (unsigned char *)glfwGetJoystickHats(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_glfwGetJoystickName(int jarg1) {
  char * jresult ;
  int arg1 ;
  char *result = 0 ;
  
  arg1 = (int)jarg1; 
  result = (char *)glfwGetJoystickName(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_glfwGetJoystickGUID(int jarg1) {
  char * jresult ;
  int arg1 ;
  char *result = 0 ;
  
  arg1 = (int)jarg1; 
  result = (char *)glfwGetJoystickGUID(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_glfwJoystickIsGamepad(int jarg1) {
  int jresult ;
  int arg1 ;
  int result;
  
  arg1 = (int)jarg1; 
  result = (int)glfwJoystickIsGamepad(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwSetJoystickCallback(void * jarg1) {
  void * jresult ;
  GLFWjoystickfun arg1 = (GLFWjoystickfun) 0 ;
  GLFWjoystickfun result;
  
  arg1 = (GLFWjoystickfun)jarg1; 
  result = (GLFWjoystickfun)glfwSetJoystickCallback(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_glfwUpdateGamepadMappings(char * jarg1) {
  int jresult ;
  char *arg1 = (char *) 0 ;
  int result;
  
  arg1 = (char *)jarg1; 
  result = (int)glfwUpdateGamepadMappings((char const *)arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_glfwGetGamepadName(int jarg1) {
  char * jresult ;
  int arg1 ;
  char *result = 0 ;
  
  arg1 = (int)jarg1; 
  result = (char *)glfwGetGamepadName(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_glfwGetGamepadState(int jarg1, void * jarg2) {
  int jresult ;
  int arg1 ;
  GLFWgamepadstate *arg2 = (GLFWgamepadstate *) 0 ;
  int result;
  
  arg1 = (int)jarg1; 
  arg2 = (GLFWgamepadstate *)jarg2; 
  result = (int)glfwGetGamepadState(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwSetClipboardString(void * jarg1, char * jarg2) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  arg2 = (char *)jarg2; 
  glfwSetClipboardString(arg1,(char const *)arg2);
}


SWIGEXPORT char * SWIGSTDCALL CSharp_glfwGetClipboardString(void * jarg1) {
  char * jresult ;
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  char *result = 0 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  result = (char *)glfwGetClipboardString(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT double SWIGSTDCALL CSharp_glfwGetTime() {
  double jresult ;
  double result;
  
  result = (double)glfwGetTime();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwSetTime(double jarg1) {
  double arg1 ;
  
  arg1 = (double)jarg1; 
  glfwSetTime(arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwGetTimerValue() {
  void * jresult ;
  uint64_t result;
  
  result = glfwGetTimerValue();
  {
    uint64_t * resultptr = (uint64_t *) malloc(sizeof(uint64_t));
    memmove(resultptr, &result, sizeof(uint64_t));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwGetTimerFrequency() {
  void * jresult ;
  uint64_t result;
  
  result = glfwGetTimerFrequency();
  {
    uint64_t * resultptr = (uint64_t *) malloc(sizeof(uint64_t));
    memmove(resultptr, &result, sizeof(uint64_t));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwMakeContextCurrent(void * jarg1) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  glfwMakeContextCurrent(arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwGetCurrentContext() {
  void * jresult ;
  GLFWwindow *result = 0 ;
  
  result = (GLFWwindow *)glfwGetCurrentContext();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwSwapBuffers(void * jarg1) {
  GLFWwindow *arg1 = (GLFWwindow *) 0 ;
  
  arg1 = (GLFWwindow *)jarg1; 
  glfwSwapBuffers(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_glfwSwapInterval(int jarg1) {
  int arg1 ;
  
  arg1 = (int)jarg1; 
  glfwSwapInterval(arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_glfwExtensionSupported(char * jarg1) {
  int jresult ;
  char *arg1 = (char *) 0 ;
  int result;
  
  arg1 = (char *)jarg1; 
  result = (int)glfwExtensionSupported((char const *)arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwGetProcAddress(char * jarg1) {
  void * jresult ;
  char *arg1 = (char *) 0 ;
  GLFWglproc result;
  
  arg1 = (char *)jarg1; 
  result = (GLFWglproc)glfwGetProcAddress((char const *)arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_glfwVulkanSupported() {
  int jresult ;
  int result;
  
  result = (int)glfwVulkanSupported();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_glfwGetRequiredInstanceExtensions(void * jarg1) {
  void * jresult ;
  uint32_t *arg1 = (uint32_t *) 0 ;
  char **result = 0 ;
  
  arg1 = (uint32_t *)jarg1; 
  result = (char **)glfwGetRequiredInstanceExtensions(arg1);
  jresult = (void *)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

